[package]
name = "faucet"
version = "0.1.0"
edition = "2024.beta"
published-at = "0xb3efcdc869b26f679b9f9f9ea27bed2fc1b0ff5c84456648f72740e04173ab0c"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
faucet = "0xb3efcdc869b26f679b9f9f9ea27bed2fc1b0ff5c84456648f72740e04173ab0c"
